[phases.setup]
nixPkgs = ["nodejs-20_x", "npm"]

[phases.install]
cmds = [
  "npm install",
  "cd client && npm install"
]

[phases.build]
cmds = [
  "cd client && npm run build"
]

[start]
cmd = "node server/index.js"

